
apiVersion: v1
kind: Service
metadata:
  name: backend-luis-tasayco-deployment
  namespace: luis-tasayco-namespace
spec:
  type: NodePort
  ports:
  - port: 30002
    targetPort: 8080
    nodePort: 30002
  selector:
    app: backend-luis-tasayco-deployment