apiVersion: v1
kind: Service
metadata:
  name: frontend-luis-tasayco-deployment
  namespace: luis-tasayco-namespace
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 4200
    nodePort: 30001
  selector:
    app: frontend-luis-tasayco-deployment
